# x = input("Enter value of x : ")
# y = input("Entyer value of y : ")
# z = int(x) + int(y)
# print(z)
# print(int(x) + int(y))
print(int(input("Enter value of x : ")) + int(input("Entyer value of y : ")))